// Auto-generated from combined.csv
// Total papers: 86

const literatureData = [
  {
    "title": "How People Prompt Generative AI to Create Interactive VR Scenes",
    "authors": "Manesh et al.",
    "xrType": "VR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.1.2 creating environments",
    "description": "allows humans to change virtual enivornment using Natural langauage",
    "risks": "2. Cross-reality security risks, 3. Manipulation of thoughts and behavior, 7. Technical limitations",
    "riskDescription": "copyright and moderation issues associated with generated scene and object. also misinterpretation of intent",
    "population": "general"
  },
  {
    "title": "Real-World Scanpaths Exhibit Long-Term Temporal Dependencies: Considerations for Contextual AI for AR Applications",
    "authors": "Burlingham et al.",
    "xrType": "AR",
    "superpowerCategory": "readmind",
    "superpowerCodes": "3.1.1 gaze",
    "description": "read minds by following gaze.",
    "risks": "1. User data awareness and transparency, 3. Manipulation of thoughts and behavior",
    "riskDescription": "privacy issues from gaze data. risks of misinterpretation of intent",
    "population": "general"
  },
  {
    "title": "PANDALens: Towards AI-Assisted In-Context Writing on OHMD During Travels",
    "authors": "Cai et al.",
    "xrType": "AR",
    "superpowerCategory": "internal, readmind",
    "superpowerCodes": "1.2.1 cognitive load, 1.2.7 memory (time capsule), 3.1.1 gaze, 3.3.1 button pressing, 3.4.1 ambient audio",
    "description": "real-time enviornment logging via gaze and ambient audio; ring button pressed to generate a blog",
    "risks": "1. User data awareness and transparency, 2. Cross-reality security risks, 3. Manipulation of thoughts and behavior",
    "riskDescription": "privacy issues due to real-time collection of multimodal data. physical risks due to using devices on the go",
    "population": "general"
  },
  {
    "title": "PaperToPlace: Transforming Instruction Documents into Spatialized and Context-Aware Mixed Reality Experiences",
    "authors": "Chen et al.",
    "xrType": "AR, MR",
    "superpowerCategory": "internal, external",
    "superpowerCodes": "1.2.1 cognitive load, 2.4.1 2d instruction -> 3d/spatial context",
    "description": "2D instruction to 3D operation (transpassing more dimenions) and reducing cognitive load",
    "risks": "1. User data awareness and transparency, 3. Manipulation of thoughts and behavior, 4. Self and social risks",
    "riskDescription": "document collection privacy; transformation from document to instruction could be inaccurate; could reduce skill development as user is not reading and comprehending the document by themselves",
    "population": "general"
  },
  {
    "title": "Scientific and Fantastical: Creating Immersive, Culturally-Relevant Learning Experiences with Augmented Reality and Large Language Models",
    "authors": "Cheng et al.",
    "xrType": "AR, MR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.1.1 adding overlays",
    "description": "changing environment by adding overlays for education",
    "risks": "1. User data awareness and transparency, 3. Manipulation of thoughts and behavior, 4. Self and social risks",
    "riskDescription": "privacy and misinformation; potential cultural insensitivity in the content",
    "population": "children"
  },
  {
    "title": "GlanceWriter: Writing Text by Glancing Over Leters with Gaze",
    "authors": "Cui et al.",
    "xrType": "VR, AR",
    "superpowerCategory": "readmind",
    "superpowerCodes": "3.1.1 gaze",
    "description": "gaze for text input",
    "risks": "1. User data awareness and transparency, 3. Manipulation of thoughts and behavior, 4. Self and social risks",
    "riskDescription": "constant gazing over different letters could be tiring for inexperienced users",
    "population": "general"
  },
  {
    "title": "LLMR: Real-time Prompting of Interactive Worlds using Large Language Models",
    "authors": "Torre et al.",
    "xrType": "VR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.1.2 creating environments, 2.1.3 changing environments",
    "description": "allows humans to create and change virtual enivornment using Natural langauage",
    "risks": "2. Cross-reality security risks, 3. Manipulation of thoughts and behavior, 7. Technical limitations",
    "riskDescription": "copyright and moderation issues associated with generated scene and object. misinterpretation of intent and misinformation; high computational resources and potential low quality generation",
    "population": "general"
  },
  {
    "title": "Exploring the Use of Large Language Model-Driven Chatbots in Virtual Reality to Train Autistic Individuals in Job Communication Skills",
    "authors": "Li et al.",
    "xrType": "VR",
    "superpowerCategory": "internal, external",
    "superpowerCodes": "1.2.5 problem solving, 2.2.1 creating social environments",
    "description": "create a social enviornment from scratch for communication skill training",
    "risks": "1. User data awareness and transparency, 3. Manipulation of thoughts and behavior",
    "riskDescription": "privacy and misinformation risk when interviewing",
    "population": "general"
  },
  {
    "title": "Towards Building Condition-Based Cross-Modality Intention-Aware Human-AI Cooperation under VR Environment",
    "authors": "He et al.",
    "xrType": "VR",
    "superpowerCategory": "readmind",
    "superpowerCodes": "3.1.1 gaze, 3.2.1 hand gesture",
    "description": "read minds by using multimodal input (eye, pointing gesture, user voice input)",
    "risks": "1. User data awareness and transparency, 3. Manipulation of thoughts and behavior",
    "riskDescription": "privacy and misinterpretation of intent",
    "population": "general"
  },
  {
    "title": "C2Ideas: Supporting Creative Interior Color Design Ideation with Large Language Model",
    "authors": "Hou et al.",
    "xrType": "VR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.1.3 changing environments",
    "description": "change the interior color design of environments",
    "risks": "3. Manipulation of thoughts and behavior, 7. Technical limitations",
    "riskDescription": "misinterpretation of intent for the design;",
    "population": "general"
  },
  {
    "title": "GazePointAR: A Context-Aware Multimodal Voice Assistant for Pronoun Disambiguation in Wearable Augmented Reality",
    "authors": "Lee et al.",
    "xrType": "AR",
    "superpowerCategory": "internal, readmind",
    "superpowerCodes": "1.2.5 problem solving, 3.1.1 gaze, 3.2.1 hand gesture",
    "description": "answer user's question by detecting user's focus through gaze and pointing",
    "risks": "1. User data awareness and transparency, 2. Cross-reality security risks, 3. Manipulation of thoughts and behavior",
    "riskDescription": "privacy risk and physical safety risk due to real time data collection and mobile usage; could produce misinformation or misinterpretation of user intent",
    "population": "general"
  },
  {
    "title": "OmniActions: Predicting Digital Actions in Response to Real-World Multimodal Sensory Inputs with LLMs",
    "authors": "Li et al.",
    "xrType": "AR",
    "superpowerCategory": "internal, readmind",
    "superpowerCodes": "1.2.1 cognitive load, 3.1.3 visual field, 3.4.1 ambient audio",
    "description": "propose actions through user's visual field and ambient sound",
    "risks": "1. User data awareness and transparency, 3. Manipulation of thoughts and behavior",
    "riskDescription": "privacy during real time data collection; misinformation and misinterpretation when predicting actions.",
    "population": "general"
  },
  {
    "title": "ClassMeta: Designing Interactive Virtual Classmate to Promote VR Classroom Participation",
    "authors": "Liu et al.",
    "xrType": "VR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.2.1 creating social environments",
    "description": "create a social environment with llm-powered virtual classmates for improved learning",
    "risks": "2. Cross-reality security risks, 3. Manipulation of thoughts and behavior, 4. Self and social risks",
    "riskDescription": "moderation risk associated with AI classmate's utterance; having AI classmates presents ethical concerns; over-active AI classmates could overload human learners and build too much peer pressure",
    "population": "student"
  },
  {
    "title": "Human I/O: Towards a Unified Approach to Detecting Situational Impairments",
    "authors": "Liu et al.",
    "xrType": "AR, MR",
    "superpowerCategory": "internal",
    "superpowerCodes": "1.2.3 logical reasoning/abstract/critical thinking",
    "description": "gives the user a clear understanding of their situation in terms of channel availability",
    "risks": "1. User data awareness and transparency, 3. Manipulation of thoughts and behavior, 7. Technical limitations",
    "riskDescription": "privacy concerns and potentially inaccurate prediction; high computational resource for making predictions",
    "population": "general"
  },
  {
    "title": "CollaXRSearch: A Collaborative Virtual Reality System for Lifelog Retrieval",
    "authors": "Ly et al.",
    "xrType": "VR",
    "superpowerCategory": "internal",
    "superpowerCodes": "1.2.7 memory (time capsule)",
    "description": "retrieve life logging through natural language",
    "risks": "",
    "riskDescription": "NA",
    "population": "general"
  },
  {
    "title": "A Mixed Reality Approach for Innovative Pair Programming Education with a Conversational AI Virtual Avatar",
    "authors": "Manfredi et al.",
    "xrType": "AR, MR",
    "superpowerCategory": "internal, external",
    "superpowerCodes": "1.2.1 cognitive load, 1.2.5 problem solving, 2.2.1 creating social environments",
    "description": "create a social enviornment from scratch for programming education by creating a pair programming avatar",
    "risks": "2. Cross-reality security risks, 3. Manipulation of thoughts and behavior, 4. Self and social risks, 7. Technical limitations",
    "riskDescription": "users may become overreliant on virtual avatar assistant, thereby reducing skill development",
    "population": "student"
  },
  {
    "title": "Storytelling: Digital Narration Enhanced by Artificial Intelligence in the Metaverse",
    "authors": "Molina-Barron et al.",
    "xrType": "VR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.2.1 creating social environments",
    "description": "create a social enviornment for education by creating a virtual school campus",
    "risks": "3. Manipulation of thoughts and behavior, 4. Self and social risks, 7. Technical limitations",
    "riskDescription": "scale of the virtual environment is so vast that it potentially overloads users; likewise for computational resources",
    "population": "student"
  },
  {
    "title": "Immersive Virtual Reality in Child Interview Skills Training: A Comparison of 2D and 3D Environments",
    "authors": "Salehi et al.",
    "xrType": "VR",
    "superpowerCategory": "internal, external",
    "superpowerCodes": "1.2.2 knowledge acquisition, 2.2.1 creating social environments",
    "description": "create a social environment with a virtual avatar for interview training. comparing performance of training between 2d and 3d environments",
    "risks": "1. User data awareness and transparency, 3. Manipulation of thoughts and behavior",
    "riskDescription": "children subjects are more vulnerable in terms of privacy awareness",
    "population": "general"
  },
  {
    "title": "Motion-I2V: Consistent and Controllable Image-to-Video Generation with Explicit Motion Modeling",
    "authors": "Shi et al.",
    "xrType": "VR, AR, MR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.4.3 transfer within visuals",
    "description": "image to video",
    "risks": "2. Cross-reality security risks",
    "riskDescription": "video generation could involve copyright infringement and inappropriate content",
    "population": "developers"
  },
  {
    "title": "LGTM: Local-to-Global Text-Driven Human Motion Diffusion Model",
    "authors": "Sun et al.",
    "xrType": "VR, AR, MR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.4.2 text to other modalities",
    "description": "text to virtual human motion",
    "risks": "2. Cross-reality security risks",
    "riskDescription": "motion generation could involve copyright infringement and inappropriate content",
    "population": "developers"
  },
  {
    "title": "AudioXtend: Assisted Reality Visual Accompaniments for Audiobook Storytelling During Everyday Routine Tasks",
    "authors": "Tan et al.",
    "xrType": "AR",
    "superpowerCategory": "internal",
    "superpowerCodes": "1.2.7 memory (time capsule)",
    "description": "use AR visual overlays to improve recall",
    "risks": "2. Cross-reality security risks, 3. Manipulation of thoughts and behavior, 4. Self and social risks",
    "riskDescription": "distaction could lead to bodily harm. visuals displayed might contain misinformaiton. users might get addicted to the experience",
    "population": "general"
  },
  {
    "title": "Choosing the Right Reality: A Comparative Analysis of Tangibility in Immersive Trauma Simulations",
    "authors": "Uhl et al.",
    "xrType": "VR, AR, MR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.2.1 creating social environments",
    "description": "create a social environment for medical training",
    "risks": "1. User data awareness and transparency, 2. Cross-reality security risks, 3. Manipulation of thoughts and behavior, 4. Self and social risks, 7. Technical limitations",
    "riskDescription": "ar see-through could be invasive to user and bystander privacy. wrong instructions could lead to physical harm. ethical concerns when providing medical assistance using llm. could be addictive and leads to loss of ability",
    "population": "medical"
  },
  {
    "title": "Virtual Heritage & AI",
    "authors": "Michael Vallance",
    "xrType": "VR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.2.1 creating social environments",
    "description": "create a social mate as tour guide",
    "risks": "3. Manipulation of thoughts and behavior",
    "riskDescription": "potential of misinformation by tour guide",
    "population": "general"
  },
  {
    "title": "Building LLM-based AI Agents in Social Virtual Reality",
    "authors": "Wan et al.",
    "xrType": "VR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.2.1 creating social environments",
    "description": "create a social npc with context-relevant responses, facial expressions and body gestures",
    "risks": "1. User data awareness and transparency, 2. Cross-reality security risks, 3. Manipulation of thoughts and behavior, 4. Self and social risks",
    "riskDescription": "llm agent causes privacy concern and could impersonate another real user. could be a harassment to the original user if the agent goes around and tells everyone things that the user said",
    "population": "general"
  },
  {
    "title": "G-VOILA: Gaze-Facilitated Information Querying in Daily Scenarios",
    "authors": "Wang et al.",
    "xrType": "AR",
    "superpowerCategory": "internal, readmind",
    "superpowerCodes": "3.1.1 gaze, 3.1.3 visual field, 3.4.1 ambient audio, 1.2.2 knowledge acquisition",
    "description": "read mind through gaze, then acquire information on the gazed target",
    "risks": "1. User data awareness and transparency, 3. Manipulation of thoughts and behavior, 4. Self and social risks, 7. Technical limitations",
    "riskDescription": "privacy issues and behavioral data exploitation from gaze data",
    "population": "general"
  },
  {
    "title": "VirtuWander: Enhancing Multi-modal Interaction for Virtual Tour Guidance through Large Language Models",
    "authors": "Wang et al.",
    "xrType": "VR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.2.1 creating social environments",
    "description": "create a social tour guide",
    "risks": "1. User data awareness and transparency, 3. Manipulation of thoughts and behavior, 4. Self and social risks",
    "riskDescription": "virtual tour guide could exploit user behavioral data and provide misinformation",
    "population": "general"
  },
  {
    "title": "ARTiST: Automated Text Simplification for Task Guidance in Augmented Reality",
    "authors": "Wu et al.",
    "xrType": "AR",
    "superpowerCategory": "internal",
    "superpowerCodes": "1.2.1 cognitive load",
    "description": "text simplification",
    "risks": "1. User data awareness and transparency, 3. Manipulation of thoughts and behavior, 4. Self and social risks",
    "riskDescription": "text simplification system could infringe privacy, provide misinfromation and might cause overreliance and reduce skills improvement",
    "population": "general"
  },
  {
    "title": "Modeling by Clipped Furniture Parts: Design with Text-Image Model with Stability Understanding",
    "authors": "Yoshida et al.",
    "xrType": "VR, AR, MR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.3.1 manipulate an object",
    "description": "text to furniture, modify or sythesize furniture",
    "risks": "2. Cross-reality security risks",
    "riskDescription": "generated furniture could infringe copyright and might be inappropriate",
    "population": "general"
  },
  {
    "title": "RoboPoint: A Vision-Language Model for Spatial Affordance Prediction for Robotics",
    "authors": "Yuan et al.",
    "xrType": "AR",
    "superpowerCategory": "",
    "superpowerCodes": "1.2.5 problem solving",
    "description": "user asks a question and receives answers and visual overays that solve the question --> automatically knowing what to do",
    "risks": "1. User data awareness and transparency, 3. Manipulation of thoughts and behavior, 4. Self and social risks, 5. Amplification of biases, 7. Technical limitations",
    "riskDescription": "possible privacy infringement and computational overload",
    "population": "general"
  },
  {
    "title": "ILLUSIONX: AN LLM-POWERED MIXED REALITY PERSONAL COMPANION",
    "authors": "Yousri et al.",
    "xrType": "MR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.2.1 creating social environments",
    "description": "creating a social companion",
    "risks": "1. User data awareness and transparency, 3. Manipulation of thoughts and behavior, 4. Self and social risks",
    "riskDescription": "personal companion privacy issue, misinformation and addiction",
    "population": "general"
  },
  {
    "title": "LLplace: The 3D Indoor Scene Layout Generation and Editing via Large Language Model",
    "authors": "Yang et al.",
    "xrType": "VR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.1.2 creating environments, 2.1.3 changing environments, 2.4.2 text to other modalities",
    "description": "text to 3D scene, create and edit 3d layouts using natural language",
    "risks": "2. Cross-reality security risks, 3. Manipulation of thoughts and behavior, 7. Technical limitations",
    "riskDescription": "generated scene could involve copyright issues. model may misinterpret user intent. also high computational cost",
    "population": "general"
  },
  {
    "title": "AID: Adapting Image2Video Diffusion Models for Instruction-guided Video Prediction",
    "authors": "Xing et al.",
    "xrType": "VR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.4.3 transfer within visuals",
    "description": "image to video",
    "risks": "7. Technical limitations",
    "riskDescription": "high computational resoureces; video generated from images might not be realistic",
    "population": "developers"
  },
  {
    "title": "UNIFIED HUMAN-SCENE INTERACTION VIA PROMPTED CHAIN-OF-CONTACTS",
    "authors": "Xiao et al.",
    "xrType": "VR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.4.2 text to other modalities",
    "description": "text to chain of contacts (points of contacts between body part and environment)",
    "risks": "7. Technical limitations",
    "riskDescription": "potential inaccurate points of contacts generated",
    "population": "developers"
  },
  {
    "title": "ARTiST: Automated Text Simplification for Task Guidance in Augmented Reality",
    "authors": "Wu et al.",
    "xrType": "AR",
    "superpowerCategory": "internal",
    "superpowerCodes": "1.2.1 cognitive load",
    "description": "simplify text",
    "risks": "1. User data awareness and transparency, 2. Cross-reality security risks, 3. Manipulation of thoughts and behavior",
    "riskDescription": "privacy and physical risk when using the device; text simplification could be inaccurate",
    "population": "general"
  },
  {
    "title": "Real-Time Multimodal Cognitive Assistant for Emergency Medical Services",
    "authors": "Weerasinghe et al.",
    "xrType": "AR",
    "superpowerCategory": "internal",
    "superpowerCodes": "1.2.1 cognitive load, 1.2.3 logical reasoning/abstract/critical thinking",
    "description": "provide treatment suggestions to first responders",
    "risks": "1. User data awareness and transparency, 2. Cross-reality security risks, 3. Manipulation of thoughts and behavior, 4. Self and social risks, 6. Lack of preparedness and standard",
    "riskDescription": "privacy and physical risk when using the device in action; potential misinformation; ethical concerns due to using LLMs in emergency medical treatment, need industry guidelines in doing so; potential overreliance on the application and reduction in skill development",
    "population": "medical"
  },
  {
    "title": "Multimodal Grounding for Embodied AI via Augmented Reality Headsets for Natural Language Driven Task Planning.",
    "authors": "Wanna et al.",
    "xrType": "AR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.3.1 manipulate an object",
    "description": "make a robot interactable, controllable and add interaface to it",
    "risks": "3. Manipulation of thoughts and behavior, 6. Lack of preparedness and standard",
    "riskDescription": "need guildeines on using LLMs to manipulate a robot for different tasks",
    "population": "robotics"
  },
  {
    "title": "Metabook: An Automatically Generated Augmented Reality Storybook Interaction System to Improve Children’s Engagement in Storytelling",
    "authors": "Wang et al.",
    "xrType": "AR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.2.1 creating social environments, 2.4.1 2d instruction -> 3d/spatial context",
    "description": "create a social avatar; text to 3d books",
    "risks": "1. User data awareness and transparency, 2. Cross-reality security risks, 3. Manipulation of thoughts and behavior, 4. Self and social risks",
    "riskDescription": "subjects are children who are more vulnerable; ethical concerns; potential copyright infringement and moderation risks when creating 3d assets; cognitive overload for children due to 3d assets",
    "population": "children"
  },
  {
    "title": "Detect2Interact: Localizing Object Key Field in Visual Question Answering (VQA) with LLMs",
    "authors": "Wang et al.",
    "xrType": "AR",
    "superpowerCategory": "internal",
    "superpowerCodes": "1.2.3 logical reasoning/abstract/critical thinking, 1.2.4 recognizing patterns, 1.2.5 problem solving",
    "description": "the model provides answers that are more contextually and spatially releveant, thereby better solving a user's questions",
    "risks": "3. Manipulation of thoughts and behavior",
    "riskDescription": "inaccurate answers",
    "population": "general"
  },
  {
    "title": "GazeNoter: Co-Piloted AR Note-Taking via Gaze Selection of LLM Suggestions to Match Users’ Intentions",
    "authors": "Tsai et al.",
    "xrType": "AR",
    "superpowerCategory": "readmind",
    "superpowerCodes": "3.1.1 gaze, 3.3.1 button pressing",
    "description": "read mind about note selection through gaze and ring button pressing",
    "risks": "1. User data awareness and transparency, 3. Manipulation of thoughts and behavior",
    "riskDescription": "privacy risk; inaccurate generation",
    "population": "general"
  },
  {
    "title": "SARA: Smart AI Reading Assistant for Reading Comprehension",
    "authors": "Thaqi et al.",
    "xrType": "AR, MR",
    "superpowerCategory": "internal, readmind",
    "superpowerCodes": "3.1.2 eye movement, 1.2.1 cognitive load, 1.2.2 knowledge acquisition",
    "description": "read mind about text that users have difficulty with through gaze and display support information",
    "risks": "1. User data awareness and transparency, 3. Manipulation of thoughts and behavior, 4. Self and social risks",
    "riskDescription": "privacy; potential misinterpretation of intent leading to cluttered interface when help is not needed; potentially reduced problem solving skills since users get help early and easily",
    "population": "general"
  },
  {
    "title": "SonifyAR: Context-Aware Sound Generation in Augmented Reality",
    "authors": "Su et al.",
    "xrType": "AR",
    "superpowerCategory": "internal",
    "superpowerCodes": "1.1.1 sound",
    "description": "users hear things that otherwise couldn't be heard",
    "risks": "7. Technical limitations",
    "riskDescription": "high computational resoureces; sounds currently need to be generated on a case-by-case basis and it's difficult to automate the matching and generation process",
    "population": "general"
  },
  {
    "title": "Voice2Action: Language Models as Agent for Efficient Real-Time Interaction in Virtual Reality",
    "authors": "Su et al.",
    "xrType": "VR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.1.3 changing environments",
    "description": "use text/voice to carry out actions and change environments",
    "risks": "3. Manipulation of thoughts and behavior",
    "riskDescription": "misinterpretation of intent for user actions",
    "population": "general"
  },
  {
    "title": "Encode-Store-Retrieve: Enhancing Memory Augmentation through Language-Encoded Egocentric Perception",
    "authors": "Shen et al.",
    "xrType": "AR",
    "superpowerCategory": "internal",
    "superpowerCodes": "1.2.7 memory (time capsule)",
    "description": "encode (describe) egocentric video as text so they can be retrieved later for memory retention",
    "risks": "1. User data awareness and transparency, 3. Manipulation of thoughts and behavior",
    "riskDescription": "transformation from video to text could be inaccurate; there is also a lot of processing to be done for the transformation",
    "population": "general"
  },
  {
    "title": "Autonomous Workflow for Multimodal Fine-Grained Training Assistants Towards Mixed Reality",
    "authors": "Pei et al.",
    "xrType": "MR",
    "superpowerCategory": "internal",
    "superpowerCodes": "1.2.1 cognitive load, 1.2.2 knowledge acquisition, 1.2.3 logical reasoning/abstract/critical thinking, 1.2.5 problem solving, 1.2.7 memory (time capsule)",
    "description": "provides multimodal instructions with memory and planning functions",
    "risks": "3. Manipulation of thoughts and behavior",
    "riskDescription": "instructions providede could be inaccurate",
    "population": "general"
  },
  {
    "title": "Integrating Large Language Models with Multimodal Virtual Reality Interfaces to Support Collaborative Human-Robot Construction Work",
    "authors": "Park et al.",
    "xrType": "VR",
    "superpowerCategory": "external, readmind",
    "superpowerCodes": "2.3.1 manipulate an object, 3.3.2 controller",
    "description": "control a robot through voice and a controller for construction tasks",
    "risks": "3. Manipulation of thoughts and behavior, 6. Lack of preparedness and standard",
    "riskDescription": "misinterpretation of user intent; controlling a robot with LLM needs guildeines",
    "population": "industry"
  },
  {
    "title": "Towards Context-aware Support for Color Vision Deficiency: An Approach Integrating LLM and AR",
    "authors": "Morita et al.",
    "xrType": "AR",
    "superpowerCategory": "internal",
    "superpowerCodes": "1.1.2 vision",
    "description": "provides contextual support for color vision deficient users",
    "risks": "2. Cross-reality security risks, 3. Manipulation of thoughts and behavior, 6. Lack of preparedness and standard",
    "riskDescription": "physical safety concerns due to outdoor usage; misinformation could be highly harmful, as illustrated in the traffic light example; need guidelines",
    "population": "color vision deficiency"
  },
  {
    "title": "Exploring a GPT-based Large Language Model for Variable Autonomy in a VR-based Human-Robot Teaming Simulation",
    "authors": "Lakhnati et al.",
    "xrType": "VR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.2.1 creating social environments",
    "description": "control multiple robots for collaborative tasks in a team-based VR environment",
    "risks": "3. Manipulation of thoughts and behavior, 4. Self and social risks, 6. Lack of preparedness and standard",
    "riskDescription": "misinterpretation of intent; ethical concerns of using LLMs to control multiple robots; need guidelines; cognitive overload from controlling multiple robots at once",
    "population": "robotics"
  },
  {
    "title": "MagicItem: Dynamic Behavior Design of Virtual Objects with Large Language Models in a Consumer Metaverse Platform",
    "authors": "Kurai et al.",
    "xrType": "VR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.3.1 manipulate an object",
    "description": "allows users to change the behaviors of objects using natural langauge",
    "risks": "2. Cross-reality security risks, 3. Manipulation of thoughts and behavior, 7. Technical limitations",
    "riskDescription": "user description of object behavior needs moderation; user intent could be misinterpreted; generation and modification fo script needs computational resources and could be inaccurate",
    "population": "general"
  },
  {
    "title": "VR-GPT: Visual Language Model for Intelligent Virtual Reality Applications",
    "authors": "Konenkov et al.",
    "xrType": "VR",
    "superpowerCategory": "internal",
    "superpowerCodes": "1.2.1 cognitive load, 1.2.3 logical reasoning/abstract/critical thinking, 1.2.5 problem solving",
    "description": "provides task instructions for users",
    "risks": "3. Manipulation of thoughts and behavior, 4. Self and social risks",
    "riskDescription": "instructions could be inaccurate; users might become overreliant and reduce skill development",
    "population": "general"
  },
  {
    "title": "RealitySummary: On-Demand Mixed Reality Document Enhancement using Large Language Models",
    "authors": "Gunturu et al.",
    "xrType": "MR",
    "superpowerCategory": "internal, external",
    "superpowerCodes": "1.2.1 cognitive load, 1.2.2 knowledge acquisition, 1.2.3 logical reasoning/abstract/critical thinking, 2.3.1 manipulate an object",
    "description": "reduce cognitive load through displaying relevant information; adding overlays and interfaces to a piece of document",
    "risks": "2. Cross-reality security risks, 3. Manipulation of thoughts and behavior, 4. Self and social risks, 7. Technical limitations",
    "riskDescription": "copyright and moderation issues with displayed information; potential misinformation; the number of tabs and amount of new information dispalyed might overload users and cause computational strain",
    "population": "general"
  },
  {
    "title": "Enabling Waypoint Generation for Collaborative Robots using LLMs and Mixed Reality",
    "authors": "Fang et al.",
    "xrType": "VR, AR, MR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.3.1 manipulate an object",
    "description": "allow users to control a robot using natural language",
    "risks": "2. Cross-reality security risks, 3. Manipulation of thoughts and behavior",
    "riskDescription": "negligence could be dangerous as users are interacting with robots; potential misinterpretation of intent",
    "population": "robotics"
  },
  {
    "title": "Augmented Object Intelligence: Making the Analog World Interactable with XR-Objects",
    "authors": "Dogan et al.",
    "xrType": "AR, MR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.3.1 manipulate an object, 2.5.1 extract info from objects",
    "description": "add overlays, which allows a range of functions, to objects",
    "risks": "1. User data awareness and transparency, 2. Cross-reality security risks, 3. Manipulation of thoughts and behavior, 4. Self and social risks",
    "riskDescription": "privacy; moderation and misinformation risks with displayed content; could overload users",
    "population": "general"
  },
  {
    "title": "Reasoning3D - Grounding and Reasoning in 3D: Fine-Grained Zero-Shot Open-Vocabulary 3D Reasoning Part Segmentation via Large Vision-Language Models",
    "authors": "Chen et al.",
    "xrType": "VR, AR",
    "superpowerCategory": "internal",
    "superpowerCodes": "1.2.2 knowledge acquisition, 1.2.4 recognizing patterns, 1.2.5 problem solving",
    "description": "highlight parts of 3d objects and generate explanations for these parts and objects",
    "risks": "3. Manipulation of thoughts and behavior, 7. Technical limitations",
    "riskDescription": "highlighted parts and generated explanations could be inaccurate;",
    "population": "general"
  },
  {
    "title": "Literature review",
    "authors": "Bozkir et al.",
    "xrType": "",
    "superpowerCategory": "",
    "superpowerCodes": "",
    "description": "",
    "risks": "",
    "riskDescription": "",
    "population": ""
  },
  {
    "title": "MISAR: A MULTIMODAL INSTRUCTIONAL SYSTEM WITH AUGMENTED REALITY",
    "authors": "Bi et al.",
    "xrType": "AR",
    "superpowerCategory": "internal",
    "superpowerCodes": "1.2.1 cognitive load, 1.2.5 problem solving",
    "description": "provides real time multimodal guidance",
    "risks": "1. User data awareness and transparency, 3. Manipulation of thoughts and behavior, 4. Self and social risks",
    "riskDescription": "privacy; misinformation and misinterpretation of intent when generating guidance; users could be overreliant and thus reduces skill development",
    "population": "general"
  },
  {
    "title": "Geometric Algebra Meets Large Language Models: Instruction-Based Transformations of Separate Meshes in 3D, Interactive and Controllable Scenes",
    "authors": "Angelis et al.",
    "xrType": "VR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.3.1 manipulate an object",
    "description": "allow users to precisely reposition objects in scenes",
    "risks": "3. Manipulation of thoughts and behavior, 7. Technical limitations",
    "riskDescription": "misinterpretation of user's repositioning intent; reposition performed could be inaccurate",
    "population": "general"
  },
  {
    "title": "PARSE-Ego4D: Personal Action Recommendation Suggestions for Egocentric Videos",
    "authors": "Abreu et al.",
    "xrType": "VR, AR",
    "superpowerCategory": "readmind",
    "superpowerCodes": "3.2.2 body movement",
    "description": "understand user movement in the scene and proposes action suggestions",
    "risks": "1. User data awareness and transparency, 3. Manipulation of thoughts and behavior",
    "riskDescription": "privacy; inaccurate action suggestion",
    "population": "general"
  },
  {
    "title": "Integrating GPT as an Assistant for Low-Cost Virtual Reality Escape-Room Games",
    "authors": "Rychert et al.",
    "xrType": "VR",
    "superpowerCategory": "internal",
    "superpowerCodes": "1.2.3 logical reasoning/abstract/critical thinking, 1.2.5 problem solving",
    "description": "helps solve complex challenges in escape room settings",
    "risks": "3. Manipulation of thoughts and behavior",
    "riskDescription": "misinformation presented",
    "population": "entertainment"
  },
  {
    "title": "Converting Physical Textbooks into Interactive and Immersive ‘Phygital’ Textbooks: A Proposed System Architecture Design for Textbook Companion Apps",
    "authors": "Saindane et al.",
    "xrType": "AR",
    "superpowerCategory": "internal, external",
    "superpowerCodes": "1.2.1 cognitive load, 1.2.2 knowledge acquisition, 1.2.3 logical reasoning/abstract/critical thinking, 2.3.1 manipulate an object, 2.4.1 2d instruction -> 3d/spatial context",
    "description": "improves knowledge acquisition via note-taking, assessment modules; make a text document interactable with virtual interfaces; creating and displaying 3D models of biological objects; track the position of the user’s device and overlay the 3D models on the real world",
    "risks": "3. Manipulation of thoughts and behavior, 4. Self and social risks",
    "riskDescription": "misinformation and cognitive overload due to added elements near text",
    "population": "general"
  },
  {
    "title": "Enhancing E-Learning Experience Through Embodied AI Tutors in Immersive Virtual Environments: A Multifaceted Approach for Personalized Educational Adaptation",
    "authors": "Sarshartehrani et al.",
    "xrType": "VR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.2.1 creating social environments",
    "description": "create a social learning environment",
    "risks": "3. Manipulation of thoughts and behavior",
    "riskDescription": "risks of information in the learning guidance",
    "population": "student"
  },
  {
    "title": "Revolutionizing Nurse Practitioner Training: Integrating Virtual Reality and Large Language Models for Enhanced Clinical Education",
    "authors": "Scott et al.",
    "xrType": "VR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.2.1 creating social environments",
    "description": "create a social nurse traning environment with realistic patients",
    "risks": "3. Manipulation of thoughts and behavior, 6. Lack of preparedness and standard",
    "riskDescription": "misinformation in training material; need guidelines for high-stake domains like healthcare",
    "population": "healthcare"
  },
  {
    "title": "Sushi with Einstein: Enhancing Hybrid Live Events with LLM-Based Virtual Humans",
    "authors": "Shoa et al.",
    "xrType": "VR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.2.1 creating social environments",
    "description": "create a social environment with a virtual panel in a hybrid event",
    "risks": "2. Cross-reality security risks, 3. Manipulation of thoughts and behavior",
    "riskDescription": "content moderation issues and ethical concerns associated with recreating historical figures;",
    "population": "general"
  },
  {
    "title": "Large Language Model-Driven Immersive Agent",
    "authors": "Singh et al.",
    "xrType": "AR",
    "superpowerCategory": "internal",
    "superpowerCodes": "1.2.1 cognitive load",
    "description": "reduces cognitive load by making recommendations during online shopping",
    "risks": "1. User data awareness and transparency, 3. Manipulation of thoughts and behavior, 4. Self and social risks",
    "riskDescription": "privacy and misinformation risks; ethical concerns with manipulating users in terms of shopping behaviors; potential cognitive overload",
    "population": "shopping"
  },
  {
    "title": "Feasibility of combining spatial computing and AI for mental health support in anxiety and depression",
    "authors": "Spiegel et al.",
    "xrType": "VR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.2.1 creating social environments",
    "description": "create a social environment with a LLM-enabled avatar for mental health therapy",
    "risks": "3. Manipulation of thoughts and behavior, 6. Lack of preparedness and standard",
    "riskDescription": "misinformation and ethical concerns risks with using LLMs in mental health therapy; need industry guidelines",
    "population": "healthcare"
  },
  {
    "title": "A language-directed virtual human motion generation approach based on musculoskeletal models",
    "authors": "Sun et al.",
    "xrType": "VR, AR, MR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.4.2 text to other modalities",
    "description": "text to virtual human motion",
    "risks": "7. Technical limitations",
    "riskDescription": "computational resources and quality of motion generated concerns;",
    "population": "developers"
  },
  {
    "title": "Improve User Experience of Augmented Reality Tour Guide Application by Using ChatGPT",
    "authors": "Xu et al.",
    "xrType": "AR",
    "superpowerCategory": "internal",
    "superpowerCodes": "1.2.1 cognitive load, 1.2.2 knowledge acquisition",
    "description": "reduces cognitive load through voice interaction and at the same time increases knowledge acquisition",
    "risks": "1. User data awareness and transparency, 3. Manipulation of thoughts and behavior",
    "riskDescription": "privacy and misinformation in tour guide explanations",
    "population": "tourists"
  },
  {
    "title": "Augmented Reality for Maintenance Tasks with ChatGPT for Automated Text-to-Action",
    "authors": "Xu et al.",
    "xrType": "AR",
    "superpowerCategory": "internal, external",
    "superpowerCodes": "1.2.1 cognitive load, 2.4.1 2d instruction -> 3d/spatial context",
    "description": "changes text to 3d action highlights and reduce cognitive load",
    "risks": "1. User data awareness and transparency, 2. Cross-reality security risks, 3. Manipulation of thoughts and behavior, 4. Self and social risks, 7. Technical limitations",
    "riskDescription": "users can become overreliant on 3d action overlays and reduces skill development; each action scenario has to be manually crafted and cannot be automated.",
    "population": "industry"
  },
  {
    "title": "Auditory VR Generative System for Non-Experts to Reproduce Human Memories Through Natural Language Interactions",
    "authors": "Yamauchi et al.",
    "xrType": "VR",
    "superpowerCategory": "internal",
    "superpowerCodes": "1.1.1 sound",
    "description": "use natural language to generate sound that reproduces memories for exposure therapy",
    "risks": "1. User data awareness and transparency, 2. Cross-reality security risks, 3. Manipulation of thoughts and behavior, 6. Lack of preparedness and standard",
    "riskDescription": "generated stimuli needs moderation; ethical concerns with using LLMs to generate therapy content; need guidelines",
    "population": "healthcare"
  },
  {
    "title": "Text2VRScene: Exploring the Framework of Automated Text-driven Generation System for VR Experience",
    "authors": "Yin et al.",
    "xrType": "VR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.1.2 creating environments",
    "description": "allows humans to generate immersive and expressive VR scenes from simple text prompts. This includes the ability to comprehend and transform natural language input into digital assets, organize them logically, and automate the entire VR scene creation process.",
    "risks": "7. Technical limitations",
    "riskDescription": "computational resources and quality of scene generated concerns;",
    "population": "general"
  },
  {
    "title": "OCTOPUS: Open-vocabulary Content Tracking and Object Placement Using Semantic Understanding in Mixed Reality",
    "authors": "Yoffe et al.",
    "xrType": "AR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.1.3 changing environments",
    "description": "using natural language to place objects at natural locations",
    "risks": "3. Manipulation of thoughts and behavior, 7. Technical limitations",
    "riskDescription": "misinterpretation of intent; computational resources and quality of objects generated concerns;",
    "population": "general"
  },
  {
    "title": "VR rehabilitation system evaluator: A fNIRS-based and LLM-enabled evaluation paradigm for Mild Cognitive Impairment",
    "authors": "Zhang et al.",
    "xrType": "VR",
    "superpowerCategory": "internal",
    "superpowerCodes": "1.2.1 cognitive load, 1.2.3 logical reasoning/abstract/critical thinking, 1.2.5 problem solving",
    "description": "through completing vr tasks, using llm to assess cognitive stimulation and generate actionable insights",
    "risks": "1. User data awareness and transparency, 3. Manipulation of thoughts and behavior, 6. Lack of preparedness and standard",
    "riskDescription": "ethical concerns with using LLMs to evalute medical conditions and need guidelines",
    "population": "healthcare"
  },
  {
    "title": "Free-form Conversation with Human and Symbolic Avatars in Mixed Reality",
    "authors": "Zhu et al.",
    "xrType": "VR, AR, MR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.2.1 creating social environments",
    "description": "create a social environment with an avatar either realistic or symbolic",
    "risks": "3. Manipulation of thoughts and behavior",
    "riskDescription": "misinformation risk",
    "population": "general"
  },
  {
    "title": "Development of Serious Game Theory Framework in Virtual Reality for Alzheimer’s Patients",
    "authors": "Zuo et al.",
    "xrType": "VR",
    "superpowerCategory": "internal",
    "superpowerCodes": "1.2.1 cognitive load, 1.2.3 logical reasoning/abstract/critical thinking",
    "description": "improve cognitive abilities of patients",
    "risks": "1. User data awareness and transparency, 3. Manipulation of thoughts and behavior, 6. Lack of preparedness and standard",
    "riskDescription": "ethical concerns with using LLMs to evalute medical conditions and need guidelines",
    "population": "healthcare"
  },
  {
    "title": "Demo: Near Real-time ChatGPT-AR",
    "authors": "Ding et al.",
    "xrType": "AR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.1.3 changing environments",
    "description": "change environments by adding virtual objects with natural languages",
    "risks": "7. Technical limitations",
    "riskDescription": "quality of generation concerns",
    "population": "general"
  },
  {
    "title": "Learning Personalized Agent for Real-Time Face-to-Face Interaction in VR",
    "authors": "Dongye et al.",
    "xrType": "VR",
    "superpowerCategory": "readmind",
    "superpowerCodes": "3.2.2 body movement",
    "description": "propose actions based on interaction distance, user head orientation and user hand pose",
    "risks": "1. User data awareness and transparency, 3. Manipulation of thoughts and behavior",
    "riskDescription": "privacy and misinterpretation of intent risks, when recommending actions",
    "population": "general"
  },
  {
    "title": "Enabling Seamless Human-Robot Collaboration in Manufacturing Using LLMs",
    "authors": "Gkournelos et al",
    "xrType": "AR",
    "superpowerCategory": "internal",
    "superpowerCodes": "1.2.1 cognitive load",
    "description": "enhance communication and collaboration between human and robots",
    "risks": "2. Cross-reality security risks, 3. Manipulation of thoughts and behavior, 6. Lack of preparedness and standard",
    "riskDescription": "physical safety concerns when interacting with robtos using LLMs; need industry guidelines",
    "population": "robotics"
  },
  {
    "title": "First Steps in Constructing an AI-Powered Digital Twin Teacher: Harnessing Large Language Models in a Metaverse Classroom",
    "authors": "Fiore et al.",
    "xrType": "VR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.2.1 creating social environments",
    "description": "create a social environment with a virtual teacher",
    "risks": "1. User data awareness and transparency, 2. Cross-reality security risks, 3. Manipulation of thoughts and behavior, 6. Lack of preparedness and standard",
    "riskDescription": "content moderation issues for virtual teacher; ethical concerns in having AI teachers tech and need industry guideliens",
    "population": "students"
  },
  {
    "title": "IVAMED: Intelligent Virtual Assistant for Medical Diagnosis",
    "authors": "Gallent-Iglesias et al.",
    "xrType": "VR",
    "superpowerCategory": "internal",
    "superpowerCodes": "1.2.3 logical reasoning/abstract/critical thinking, 1.2.5 problem solving",
    "description": "provide medical diagnosis using natural language",
    "risks": "1. User data awareness and transparency, 3. Manipulation of thoughts and behavior, 6. Lack of preparedness and standard",
    "riskDescription": "ethical concerns with using LLMs for medical diagnosis; need industry guidelines",
    "population": "healthcare"
  },
  {
    "title": "AllyChat: Developing a VR Conversational AI Agent Using Few-Shot Learning to Support Individuals with Intellectual Disabilities",
    "authors": "Garcia-Pi et al.",
    "xrType": "VR",
    "superpowerCategory": "internal, external",
    "superpowerCodes": "1.2.2 knowledge acquisition, 1.2.3 logical reasoning/abstract/critical thinking, 2.2.1 creating social environments",
    "description": "create a social environment with a virtual avatar for job interview training",
    "risks": "1. User data awareness and transparency, 3. Manipulation of thoughts and behavior",
    "riskDescription": "privacy and misinformation concerns with the training material provided by the virtual agent",
    "population": "general"
  },
  {
    "title": "DreamCodeVR: Towards Democratizing Behavior Design in Virtual Reality with Speech-Driven Programming",
    "authors": "Giunchi et al.",
    "xrType": "VR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.1.3 changing environments, 2.3.1 manipulate an object",
    "description": "allow users to change the appearance, behavior and state of objects using natural language",
    "risks": "2. Cross-reality security risks, 7. Technical limitations",
    "riskDescription": "content moderation issues with user-modified objects; computational resources risks and quality of generated objects concerns",
    "population": "general"
  },
  {
    "title": "Keep Gesturing: A Game for Pragmatic Communication",
    "authors": "Gulyas et al.",
    "xrType": "AR",
    "superpowerCategory": "readmind",
    "superpowerCodes": "3.2.1 hand gesture",
    "description": "enable human-LLM communication through hand gesture",
    "risks": "3. Manipulation of thoughts and behavior",
    "riskDescription": "inaccurate intent identificaiton",
    "population": "entertainment"
  },
  {
    "title": "EyeClick: A Robust Two-Step Eye-Hand Interaction for Text Entry in Augmented Reality Glasses",
    "authors": "Guo et al.",
    "xrType": "AR",
    "superpowerCategory": "readmind",
    "superpowerCodes": "3.1.1 gaze, 3.3.2 controller",
    "description": "read mind with user's gaze and a controller",
    "risks": "1. User data awareness and transparency, 3. Manipulation of thoughts and behavior, 4. Self and social risks",
    "riskDescription": "cognitive overload due to coordination between gazing and controller input for inexperienced users",
    "population": "general"
  },
  {
    "title": "Sensor2Scene: Foundation Model-driven Interactive Realities",
    "authors": "Guo et al.",
    "xrType": "AR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.1.2 creating environments, 2.4.2 text to other modalities",
    "description": "an AI agent leverages large language models (LLMs) to decode subtle information from sensor data, constructing detailed scene descriptions for visualization. To enable these scenes to be rendered in AR, we decompose the scene creation process into tasks of text-to-3D model generation and spatial composition, allowing new AR scenes to be sketched from the descriptions; The framework acquires sensor data and environmental information from the sensor readings and user input, then transforming these intangible environmental data into contextually relevant, augmented visuals in 3D AR scene.",
    "risks": "2. Cross-reality security risks, 7. Technical limitations",
    "riskDescription": "generated scenes could infringement copyright; moderation issues with generation;",
    "population": "general"
  },
  {
    "title": "ARELE-bot: Inclusive Learning of Spanish as a Foreign Language Through a Mobile App Integrating Augmented Reality and ChatGPT",
    "authors": "Hajahmadi et al.",
    "xrType": "AR",
    "superpowerCategory": "internal, external",
    "superpowerCodes": "2.2.1 creating social environments, 1.2.2 knowledge acquisition",
    "description": "create a social environment with a virtual avatar for language education",
    "risks": "1. User data awareness and transparency, 3. Manipulation of thoughts and behavior",
    "riskDescription": "privacy and misinformation risks with using LLMs to teach language",
    "population": "student"
  },
  {
    "title": "FluencyAR: Augmented Reality Language Immersion",
    "authors": "Hollingworth et al",
    "xrType": "AR",
    "superpowerCategory": "internal, external",
    "superpowerCodes": "2.2.1 creating social environments, 1.2.2 knowledge acquisition",
    "description": "create a social environment for practicing second language learning using real-time prompts and feedback through AR, emulating language immersion and facilitating contextual conversations.",
    "risks": "1. User data awareness and transparency, 3. Manipulation of thoughts and behavior, 7. Technical limitations",
    "riskDescription": "scenes seem to be manually crafted, which needs resources",
    "population": "student"
  },
  {
    "title": "Towards Using Generative AI for Facilitating Image Creation in Spatial Augmented Reality",
    "authors": "Hu et al.",
    "xrType": "AR",
    "superpowerCategory": "external",
    "superpowerCodes": "2.1.3 changing environments",
    "description": "Enhances the ability to create and project high-quality images onto physical objects in SAR environments using natural language prompts, thereby transforming and optimizing the visual attributes of those objects.",
    "risks": "2. Cross-reality security risks, 7. Technical limitations",
    "riskDescription": "copyright and moderation issues with generated images; potential quality issues",
    "population": "designers"
  }
];
